def myAccounts():
    return [
        "svk",
        "svk-1",
        "svk-2",
        "svk-4",
        "svk-9",
        "fbsvk",
        "rainman",
        "rainman-1",
        "rainman-2",
        "rainman-3",
        "rainman-4",
        "rainman-5",
        "rainman1",
        "rainman2",
        "rainman3",
        "rainman4",
        "rainman5",
        "rainmac",
        "rainmac-1",
        "witness.svk",
        "laivi",
        "susanne",
        "gbert"
    ]
